name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: runtest
      run: make runtest
    - name: Login to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v5 
      with:
          image: 9756698611/sunday
          registry: docker.io	
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

